### ISSUE TITLE
请教下，在外面做一个登录页面进入主页StackNavigator 怎么弄

### ISSUE THREAD

**Issue by longkehuawei** [spicyboiledfish/peanutWIFI#2]
请教下，在外面做一个登录页面进入主页StackNavigator 怎么弄

**Comment by spicyboiledfish** [comment]
将登陆模块和Tab合并成一个navigator作为跟视图，可参考：[https://reactnavigation.org/docs/en/modal.html](https://reactnavigation.org/docs/en/modal.html)
