### ISSUE TITLE
Android手机上Tab 切换，按返回键，会回到首页，不会立马退出

### ISSUE THREAD

**Issue by longkehuawei** [spicyboiledfish/peanutWIFI#4]
Android手机上Tab 切换，按返回键，会回到首页，不会立马退出

**Comment by spicyboiledfish** [comment]
返回键返回两次可以退出吗

**Comment by longkehuawei** [comment]
是这样的，在第二页的时候，我按返回键，它返回到第一页，然后再按返回键，才退出
正常应该Tab在第一页和第二页，第三页，第四，他们都是平级的，返回不需要返回到首页才能退出

**Comment by yirikanjinchanganhua** [comment]
萌新围观学习，坐等大佬更新

**Comment by longkehuawei** [comment]
大佬解决了么？

**Comment by longkehuawei** [comment]
backBehavior: 'none', // 按 back 键是否跳转到第一个Tab(首页)， none 为不跳转

我试了这个可以

**Comment by longkehuawei** [comment]
咨询一个问题，加入从页面A -》B->C  从B跳转到C的时候要关闭掉A这个怎么弄？

**Comment by spicyboiledfish** [comment]
使用backBehavior: 'none',
从A->B->C；如果从B->C之后，你不在希望再跳回到A，那么可以直接写this.props.navigation.navigate('Next')去到某一个指定的页面；或者可以在点击返回的事件中，对接收到页面的route参数后做判断，去到指定的页面
